# Generated by Django 5.2.4 on 2025-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('film_or_series', models.BooleanField(default=True)),
                ('watched', models.BooleanField(default=False)),
                ('score', models.IntegerField(null=True)),
                ('review', models.TextField(null=True)),
                ('actor', models.ManyToManyField(related_name='actor_name', to='filmr.actor')),
                ('director', models.ManyToManyField(related_name='director_name', to='filmr.director')),
                ('genre', models.ManyToManyField(related_name='genre_name', to='filmr.genre')),
            ],
        ),
    ]
