# Generated by Django 5.2.4 on 2025-08-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(null=True, related_name='actor_name', to='filmr.actor'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(null=True, related_name='director_name', to='filmr.director'),
        ),
    ]
